# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Nandeesh Mp'
tagline:             'Developer & Open Source Enthusiast'
description:         'Developer & Open Source Enthusiast'
url:                 http://www.nandeesh.com
baseurl:             'http://www.nandeesh.com'

# About/contact
author:
  name:              'Nandeesh Mp'
  url:               https://www.twitter.com/nandeeshmp
  email:             coder@nandeesh.com

paginate:            12

# Custom vars
version:             1.0.0
