# Setup
title:               Nandeesh MP
tagline:             'AI Solutions Architect | Senior Software Engineer'
description:         'Sr Software Engineer with a decade of experience. Specializing in Generative AI, LangChain, LLMs, RAG, and Prompt Engineering.'
url:                 https://nandeesh.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nandeesh MP
  url:               https://nandeesh.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
